<?php

namespace app\modules\osmb\models;

use Yii;
use yii\helpers\Json;


/**
 * This is the model class for table "oplata".
 *
 * @property integer $id
 * @property integer $oplata
 * @property integer $subsid
 * @property string $raschet_id
 *
 * @property Raschet $raschet
 */
class Oplata extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'oplata';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['oplata', 'subsid', 'raschet_id'], 'integer'],
            [['raschet_id'], 'required'],
            [['raschet_id'], 'exist', 'skipOnError' => true, 'targetClass' => Raschet::className(), 'targetAttribute' => ['raschet_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'oplata' => Yii::t('app', 'Oplata'),
            'subsid' => Yii::t('app', 'Subsid'),
            'raschet_id' => Yii::t('app', 'Raschet ID'),
        ];
    }

    public static function find()
    {
        $find = parent::find();
        $roles = Yii::$app->authManager->getRolesByUser(Yii::$app->user->id);
        if (isset($roles['accountant'])) {
            $raschet = array();
            foreach (Raschet::find()->all() as $item) {
                $raschet[] = $item->id;
            }
            return $find->andWhere(['raschet_id' => $raschet]);
        }
        return $find;
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRaschet()
    {
        return $this->hasOne(Raschet::className(), ['id' => 'raschet_id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($changedAttributes) {

            $this->editOneRaschet();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function editOneRaschet()
    {
        $raschets = Raschet::find()->all();
        foreach ($raschets as $raschet) {

            if ($this->raschet_id == $raschet->id){
                $raschet->summ_oplata += $this->oplata;
                $raschet->summ_subsid += $this->subsid;
                if (!$raschet->save()) {
                    Yii::error(Json::encode($raschet->errors));
                }
            }

        }return;
        //var_dump($this); die();
    }

}
